.\" Manpage for Chat
.\" Contact ubergeek@phoenix.thunix.cf to correct errors or typos.
.TH man 8 "04 January 2019" "1.0" "Thunix chat man page"
.SH NAME
chat \- chat script
.SH SYNOPSIS
chat
.SH DESCRIPTION
This is a simple script to launch weechat for new users, and get them into the correct channel for chat and support.
.SH BUGS
* If you have a customized list of servers in your weechat config already, this may try to connect you twice, and you'll have two nicks going at once, which will be confusing.  Once you've customized weechat to your liking, just invoke 'weechat' or 'weechat-curses'.
.SH SEE ALSO
weechat(8) 
.SH AUTHOR
Uber Geek (ubergeek@phoenix.thunix.cf)
